# Generated by Django 5.2.8 on 2025-11-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='password',
            field=models.CharField(blank=True, help_text='Deixe em branco para uma galeria pública.', max_length=128, null=True),
        ),
    ]
